name: mothur
owner: iuc
description: Mothur wrappers
long_description: |
    The mothur project seeks to offers a single piece of open-source, expandable software to fill the bioinformatics needs of the microbial ecology community.
    We have incorporated the functionality of dotur, sons, treeclimber, s-libshuff, unifrac, and much more.
    In addition to improving the flexibility of these algorithms, we have added a number of other features including calculators and visualization tools.
categories:
- Metagenomics
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/mothur
homepage_url: http://www.mothur.org
type: unrestricted
include:
- strip_components: 1
  source:
  - ../macros.xml
  - ../test-data/
  - ../tool-data/
  - ../tool_data_table_conf.xml.sample
- strip_components: 2
  source:
  - ../mothur3/
suite:
  name: "suite_mothur_part3"
  description: "A suite of tools designed to bring the mothur project into Galaxy."
  long_description: |
      The mothur project seeks to offers a single piece of open-source, expandable software to fill the bioinformatics needs of the microbial ecology community.
      We have incorporated the functionality of dotur, sons, treeclimber, s-libshuff, unifrac, and much more.
      In addition to improving the flexibility of these algorithms, we have added a number of other features including calculators and visualization tools.
